export const UPDATE_FORM_COLOR_VALUE = 'UPDATE_FORM_COLOR_VALUE';
export const UPDATE_FORM_COLOR_SCHEME_VALUE = 'UPDATE_FORM_COLOR_SCHEME_VALUE';
export const UPDATE_PALETTE = 'UPDATE_PALETTE';

export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
